
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/home_credit_scoring', 'batch_prediction_src/']
options:
  machineType: 'N1_HIGHCPU_8'
tags: ['latest']
images: ['gcr.io/$PROJECT_ID/home_credit_scoring']
